# Generated by Django 5.2.6 on 2025-10-09 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('form_builder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecordHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='form_builder.form', verbose_name='فرم')),
            ],
        ),
        migrations.CreateModel(
            name='RecordItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='records.recordheader', verbose_name='هدر مربوطه')),
            ],
        ),
        migrations.CreateModel(
            name='HeaderValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_text', models.TextField(blank=True, null=True)),
                ('value_number', models.DecimalField(blank=True, decimal_places=5, max_digits=20, null=True)),
                ('value_date_gregorian', models.DateField(blank=True, null=True)),
                ('value_date_jalali', models.CharField(blank=True, max_length=10, null=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='header_values', to='form_builder.field')),
                ('header', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='records.recordheader')),
            ],
            options={
                'unique_together': {('header', 'field')},
            },
        ),
        migrations.CreateModel(
            name='ItemValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_text', models.TextField(blank=True, null=True)),
                ('value_number', models.DecimalField(blank=True, decimal_places=5, max_digits=20, null=True)),
                ('value_date_gregorian', models.DateField(blank=True, null=True)),
                ('value_date_jalali', models.CharField(blank=True, max_length=10, null=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_values', to='form_builder.field')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='records.recorditem')),
            ],
            options={
                'unique_together': {('item', 'field')},
            },
        ),
    ]
