# Generated by Django 5.2.6 on 2025-10-09 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='کد یکتای فرم')),
                ('name', models.CharField(max_length=100, verbose_name='نام فرم')),
                ('form_type', models.CharField(choices=[('SINGLE_SECTION', 'یک\u200cبخشی (فقط هدر)'), ('DOUBLE_SECTION', 'دوبخشی (هدر + اقلام)')], default='SINGLE_SECTION', max_length=20, verbose_name='نوع فرم')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('display_order', models.PositiveIntegerField(default=10, verbose_name='ترتیب نمایش')),
                ('color', models.CharField(default='#FFFFFF', max_length=7, verbose_name='کد رنگ هگزادسیمال')),
            ],
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('HEADER', 'هدر'), ('ITEM', 'اقلام/ردیف\u200cها')], default='HEADER', max_length=10, verbose_name='بخش فرم')),
                ('code', models.CharField(max_length=50, verbose_name='کد یکتای فیلد در فرم')),
                ('name', models.CharField(max_length=100, verbose_name='نام فیلد')),
                ('field_type', models.CharField(choices=[('NUMBER', 'عددی'), ('TEXT', 'متنی'), ('DATE', 'تاریخی'), ('LOOKUP', 'لوکاپ'), ('LOOKUP_DISPLAY', 'لوکاپ نمایشی')], max_length=20, verbose_name='نوع فیلد')),
                ('is_required', models.BooleanField(default=False, verbose_name='اجباری')),
                ('is_unique', models.BooleanField(default=False, verbose_name='غیرتکراری')),
                ('is_readonly_on_edit', models.BooleanField(default=False, verbose_name='غیرقابل ویرایش در حالت ویرایش')),
                ('has_auto_increment', models.BooleanField(default=False, verbose_name='پیشنهاد افزایش خودکار دارد؟')),
                ('is_computed', models.BooleanField(default=False, verbose_name='محاسباتی است؟')),
                ('computation_formula', models.TextField(blank=True, null=True, verbose_name='فرمول محاسبه')),
                ('computation_level', models.CharField(blank=True, choices=[('ITEM', 'سطح آیتم'), ('AGGREGATE', 'سطح تجمعی (هدر)'), ('HEADER', 'سطح هدر')], max_length=10, null=True, verbose_name='سطح محاسبه')),
                ('computation_order', models.PositiveIntegerField(default=1, verbose_name='ترتیب محاسبه')),
                ('lookup_display_field', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='form_builder.field', verbose_name='فیلد نمایشی (برای لوکاپ)')),
                ('lookup_reference_field', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='form_builder.field', verbose_name='فیلد مرجع (برای لوکاپ)')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='form_builder.form', verbose_name='فرم مربوطه')),
                ('lookup_form', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lookup_source_for', to='form_builder.form', verbose_name='فرم مرجع (برای لوکاپ)')),
            ],
            options={
                'unique_together': {('form', 'code')},
            },
        ),
    ]
